version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: lorry-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lorrydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: lorry-backend
    depends_on:
      - postgres
    ports:
      - "1001:1001"
    environment:
      JDBC_URL: jdbc:postgresql://postgres:5432/lorrydb
      DB_USER: postgres
      DB_PASS: postgres
    restart: unless-stopped

volumes:
  postgres_data:
