server:
  port: 1001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lorrydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: lorryuser
    password: Lorry@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
